### ISSUE TITLE
Remove dependencies from child projects

### ISSUE THREAD

**Issue by mackstar** [sky-uk/blackjack-toolbelt#16]
After `init`ing a project the child project contains the following dependencies in it's package.json that I feel should be part of the command line tool project. The dependencies I would like to remove as I believe would be common in nearly every project are:

```
    "babel-loader": "^6.2.4",
    "babel-core": "^6.7.4",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.7.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.7.2",
    "css-loader": "^0.23.1",
    "node-sass": "^3.6.0",
    "react": "^0.14.8",
    "react-dom": "^15.0.1",
    "sass-loader": "^3.2.0",
    "sky-blackjack-tools": "github:sky-uk/blackjack-tools",
    "style-loader": "^0.13.1"
```

These should route through to the command line app.

**Comment by joshnesbitt** [comment]
Agree. Need to sort this, NPM isn't playing ball at the moment.

**Comment by mackstar** [comment]
I think this is in a good place now? Still needs polishing? Shall we close..?

**Comment by joshnesbitt** [comment]
I think it's working well for now. Will close 👍
