### ISSUE TITLE
Add -v (version) for convience

### ISSUE THREAD

**Issue by romidane** [sky-uk/blackjack-toolbelt#30]
There needs to be a way for users to know what version of the app they are running in case certain version in the future become unstable but mainly for convenience

**Comment by joshnesbitt** [comment]
This should work with `--version`, assume that's why you closed it?

**Comment by romidane** [comment]
Yep.. I had the whole thing setup wrong. my bad ^.^

**Comment by joshnesbitt** [comment]
No problem.
