### ISSUE TITLE
karma test still requires some dependencies inside child projects

### ISSUE THREAD

**Issue by yjcxy12** [sky-uk/blackjack-toolbelt#37]
At the moment, it still needs `babel-core` `babel-loader` `babel-presets-xxx` `isparta-loader` etc to run tests in `blackjack-accordion#v1`. If these dependencies are omitted, `test` task will error out. It seems that karma config cannot pickup packages from toolbelt directory.

**Comment by joshnesbitt** [comment]
I've not looked at the `blackjack-accordion` repo recently. Might be worth revisiting it. We used the `sky-uk/blackjack-sign-in` component as our first test project for the toolbelt.

**Comment by yjcxy12** [comment]
Installing toolbelt locally as well as globally solved the issue as it installs all the required dependancies.
Closing the issue.

**Comment by joshnesbitt** [comment]
OK. This probably isn't ideal, we could do with taking a look at it at some point.
