### ISSUE TITLE
ESLint throws error for some Chai assertions

### ISSUE THREAD

**Issue by thomaslloyd** [sky-uk/blackjack-toolbelt#39]
Our current lint setup throws a [`no-unused-expressions`][0] error for a bunch of Chai assertions, e.g;
```
expect(val).to.be.ok;
expect(val).to.be.undefined;
```
There's a [discussion about possible solutions][1] on the ESLint github repo. It seems either we need to turn off the rule or use a Chai plugin such as [chai-lint][2] or [dirty-chai][3] to convert the assertions. Both of these solutions seem a bit wrong. Anyone have any thoughts on how we should fix this?

[0]: http://eslint.org/docs/rules/no-unused-expressions
[1]: https://github.com/eslint/eslint/issues/2102
[2]: https://github.com/LFDM/chai-lint
[3]: https://github.com/prodatakey/dirty-chai

**Comment by joshnesbitt** [comment]
I think I'd be happy turning off the rule, as it's quite an edge case. Over to @mackstar.

**Comment by thomaslloyd** [comment]
@joshnesbitt I don't actually agree that it's an edge case rule. It helps a lot with arrow functions. For instance `const fn = () => someValue;` works just fine, but it's easy to forget to add the return keyword when extending the body to do something before returning, like below:

```
const fn = () => {
    // some addition to the function

    someValue
}
```

Now the function returns undefined, but is caught by this lint error.

**Comment by mackstar** [comment]
Would putting exceptions for the rule in comments not be a short term fix? Would rather do this until we find out other's experience and opinions on this. I do feel the rule is helpful, but using a plugin doesn't feel right either. Either way we choose will be a compromise.

**Comment by thomaslloyd** [comment]
@mackstar Yeah I think I'd be happiest doing that for the time being. It's a shame there's no good solution for this.

**Comment by joshnesbitt** [comment]
@thomaslloyd apologies I didn't realise the rule covered other scenarios like the one you've posted. I agree it's not ideal, but for now if we disable the rule we can see how other people feel about it. Linting is fantastic for code quality, but we shouldn't let it get in the way of building things.
