### ISSUE TITLE
Investigate issues with Node 6.X

### ISSUE THREAD

**Issue by joshnesbitt** [sky-uk/blackjack-toolbelt#52]

**Comment by romidane** [comment]
@joshnesbitt I've just tried this out. I'm currently running Node v6.2.0. To get this work what you need to do is delete the node_modules folder in both your component and the blackjack-toolbelt and re-install them

**Comment by joshnesbitt** [comment]
So potentially a non-issue @romidane?

**Comment by romidane** [comment]
@joshnesbitt. Yes pottentially :)

**Comment by joshnesbitt** [comment]
It fixed my problems too. Closing for now :)

**Comment by romidane** [comment]
Great! 😄
